//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeClass
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class database_practiceclassEntities : DbContext
    {
        public database_practiceclassEntities()
            : base("name=database_practiceclassEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<table_course> table_course { get; set; }
        public virtual DbSet<table_practice> table_practice { get; set; }
        public virtual DbSet<table_practiceclass> table_practiceclass { get; set; }
        public virtual DbSet<table_practicestudent> table_practicestudent { get; set; }
        public virtual DbSet<table_professor> table_professor { get; set; }
        public virtual DbSet<table_quiz> table_quiz { get; set; }
        public virtual DbSet<table_quizstudent> table_quizstudent { get; set; }
        public virtual DbSet<table_resource> table_resource { get; set; }
        public virtual DbSet<table_student> table_student { get; set; }
        public virtual DbSet<table_studentpracticeclass> table_studentpracticeclass { get; set; }
        public virtual DbSet<table_user> table_user { get; set; }
        public virtual DbSet<viewadminlistprofessor> viewadminlistprofessor { get; set; }
        public virtual DbSet<viewadminliststudent> viewadminliststudent { get; set; }
        public virtual DbSet<viewlistclass> viewlistclass { get; set; }
        public virtual DbSet<viewlistclassmember> viewlistclassmember { get; set; }
        public virtual DbSet<viewlistcourseresourse> viewlistcourseresourse { get; set; }
        public virtual DbSet<viewlistpractice> viewlistpractice { get; set; }
        public virtual DbSet<viewlistpracticesolved> viewlistpracticesolved { get; set; }
        public virtual DbSet<viewlistquiz> viewlistquiz { get; set; }
        public virtual DbSet<viewlistquizstudent> viewlistquizstudent { get; set; }
        public virtual DbSet<viewstudentlistclass> viewstudentlistclass { get; set; }
        public virtual DbSet<viewstudentlistpractice> viewstudentlistpractice { get; set; }
        public virtual DbSet<viewstudentlistquiz> viewstudentlistquiz { get; set; }
    }
}
