//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_practiceclass
    {
        public int idTable { get; set; }
        public Nullable<bool> status { get; set; }
        public string idCourse { get; set; }
        public string idProfessor { get; set; }
        public string idTA { get; set; }
        public short groupeNumberPracticeClass { get; set; }
        public bool termPracticeClass { get; set; }
        public short numberYearFromStart { get; set; }
        public bool deleted { get; set; }
    
        public virtual table_course table_course { get; set; }
        public virtual table_professor table_professor { get; set; }
        public virtual table_student table_student { get; set; }
    }
}
