//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewlistcourseresourse
    {
        public string idCourse { get; set; }
        public string nameCourse { get; set; }
        public string nameResource { get; set; }
        public string linkResource { get; set; }
        public short numberResource { get; set; }
        public bool deleted { get; set; }
    }
}
