//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewlistclass
    {
        public short groupeNumberPracticeClass { get; set; }
        public bool termPracticeClass { get; set; }
        public short numberYearFromStart { get; set; }
        public string idProfessor { get; set; }
        public string prffn { get; set; }
        public string pfln { get; set; }
        public string idTA { get; set; }
        public string tafn { get; set; }
        public string taln { get; set; }
        public Nullable<bool> status { get; set; }
        public string nameCourse { get; set; }
        public Nullable<double> AVG_c_gradePracticeClassStudent_ { get; set; }
        public bool classDel { get; set; }
        public bool stuDel { get; set; }
    }
}
