//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewlistclassmember
    {
        public Nullable<float> gradePracticeClassStudent { get; set; }
        public short groupeNumberPracticeClass { get; set; }
        public bool termPracticeClass { get; set; }
        public short numberYearFromStart { get; set; }
        public string idStudent { get; set; }
        public string stufn { get; set; }
        public string stuln { get; set; }
        public bool stuDel { get; set; }
    }
}
