//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewlistpractice
    {
        public short partPractice { get; set; }
        public short numberPractice { get; set; }
        public string linkPractice { get; set; }
        public bool termPracticeClass { get; set; }
        public short numberYearFromStart { get; set; }
        public short groupeNumberPracticeClass { get; set; }
        public Nullable<decimal> AVG_b_gradePracticeStudent_ { get; set; }
        public bool pracDel { get; set; }
        public bool pracStuDel { get; set; }
    }
}
