//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewstudentlistclass
    {
        public Nullable<float> gradePracticeClassStudent { get; set; }
        public short groupeNumberPracticeClass { get; set; }
        public bool termPracticeClass { get; set; }
        public short numberYearFromStart { get; set; }
        public string idStudent { get; set; }
        public string idCourse { get; set; }
        public string nameCourse { get; set; }
        public string idProfessor { get; set; }
        public string proffnam { get; set; }
        public string proflnam { get; set; }
        public string idTA { get; set; }
        public string tafn { get; set; }
        public string talnm { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
