//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewlistquizstudent
    {
        public short numberQuiz { get; set; }
        public Nullable<System.DateTime> dateQuiz { get; set; }
        public bool termPracticeClass { get; set; }
        public short numberYearFromStart { get; set; }
        public short groupeNumberPracticeClass { get; set; }
        public Nullable<short> gradeQuizStudent { get; set; }
        public string idUser { get; set; }
        public string firstNameUser { get; set; }
        public string lastNameUser { get; set; }
        public bool quizdDel { get; set; }
        public bool quizStuDel { get; set; }
    }
}
