//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewstudentlistpractice
    {
        public Nullable<short> partPractice { get; set; }
        public Nullable<short> numberPractice { get; set; }
        public string linkPractice { get; set; }
        public Nullable<bool> termPracticeClass { get; set; }
        public Nullable<short> numberYearFromStart { get; set; }
        public Nullable<short> groupeNumberPracticeClass { get; set; }
        public Nullable<short> gradePracticeStudent { get; set; }
        public string idStudent { get; set; }
        public string linkSolvedPractice { get; set; }
        public System.DateTime timePracticeStudent { get; set; }
        public bool @checked { get; set; }
    }
}
