//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewadminlistprofessor
    {
        public string idUser { get; set; }
        public string firstNameUser { get; set; }
        public string lastNameUser { get; set; }
        public string password { get; set; }
    }
}
